/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateAccountExample */

#ifndef _Included_CreateAccountExample
#define _Included_CreateAccountExample
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     CreateAccountExample
   * Method:    nativeMain
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_com_hedera_hashgraph_sdk_cpp_examples_CreateAccountExample_createAccountExample(JNIEnv*,
                                                                                                              jobject);

#ifdef __cplusplus
}
#endif
#endif
