// SPDX-License-Identifier: Apache-2.0
#ifndef HIERO_SDK_CPP_TRANSACTION_TYPE_H_
#define HIERO_SDK_CPP_TRANSACTION_TYPE_H_

namespace Hiero
{
/**
 * Enumeration of all transaction types.
 */
enum TransactionType : int
{
  UNKNOWN_TRANSACTION = -1,
  ACCOUNT_ALLOWANCE_APPROVE_TRANSACTION,
  ACCOUNT_ALLOWANCE_DELETE_TRANSACTION,
  ACCOUNT_CREATE_TRANSACTION,
  ACCOUNT_DELETE_TRANSACTION,
  ACCOUNT_UPDATE_TRANSACTION,
  CONTRACT_CREATE_TRANSACTION,
  CONTRACT_DELETE_TRANSACTION,
  CONTRACT_EXECUTE_TRANSACTION,
  CONTRACT_UPDATE_TRANSACTION,
  ETHEREUM_TRANSACTION,
  FILE_APPEND_TRANSACTION,
  FILE_CREATE_TRANSACTION,
  FILE_DELETE_TRANSACTION,
  FILE_UPDATE_TRANSACTION,
  FREEZE_TRANSACTION,
  NODE_CREATE_TRANSACTION,
  NODE_DELETE_TRANSACTION,
  NODE_UPDATE_TRANSACTION,
  PRNG_TRANSACTION,
  SCHEDULE_CREATE_TRANSACTION,
  SCHEDULE_DELETE_TRANSACTION,
  SCHEDULE_SIGN_TRANSACTION,
  SYSTEM_DELETE_TRANSACTION,
  SYSTEM_UNDELETE_TRANSACTION,
  TOKEN_AIRDROP_TRANSACTION,
  TOKEN_ASSOCIATE_TRANSACTION,
  TOKEN_BURN_TRANSACTION,
  TOKEN_CANCEL_AIRDROP_TRANSACTION,
  TOKEN_CLAIM_AIRDROP_TRANSACTION,
  TOKEN_CREATE_TRANSACTION,
  TOKEN_DELETE_TRANSACTION,
  TOKEN_DISSOCIATE_TRANSACTION,
  TOKEN_FEE_SCHEDULE_UPDATE_TRANSACTION,
  TOKEN_FREEZE_TRANSACTION,
  TOKEN_GRANT_KYC_TRANSACTION,
  TOKEN_MINT_TRANSACTION,
  TOKEN_PAUSE_TRANSACTION,
  TOKEN_REJECT_TRANSACTION,
  TOKEN_REVOKE_KYC_TRANSACTION,
  TOKEN_UNFREEZE_TRANSACTION,
  TOKEN_UNPAUSE_TRANSACTION,
  TOKEN_UPDATE_NFTS_TRANSACTION,
  TOKEN_UPDATE_TRANSACTION,
  TOKEN_WIPE_TRANSACTION,
  TOPIC_CREATE_TRANSACTION,
  TOPIC_DELETE_TRANSACTION,
  TOPIC_MESSAGE_SUBMIT_TRANSACTION,
  TOPIC_UPDATE_TRANSACTION,
  TRANSFER_TRANSACTION
};

} // namespace Hiero

#endif // HIERO_SDK_CPP_TRANSACTION_TYPE_H_
