name: "Clang-Format Check"
on:
  workflow_call:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  formatting-check:
    name: Formatting Check
    runs-on:
      - self-hosted
      - "${{ matrix.os }}"
      - xlarge
      - ephemeral
    strategy:
      matrix:
        path:
          - 'sdk'
          - 'tck'
    steps:
      - uses: actions/checkout@v3
      - name: Run Clang-Format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "17""
          check-path: ${{ matrix.path }}